// Generated by gencpp from file pr2_robot/GetFloatArrayFeatureResponse.msg
// DO NOT EDIT!


#ifndef PR2_ROBOT_MESSAGE_GETFLOATARRAYFEATURERESPONSE_H
#define PR2_ROBOT_MESSAGE_GETFLOATARRAYFEATURERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pr2_robot
{
template <class ContainerAllocator>
struct GetFloatArrayFeatureResponse_
{
  typedef GetFloatArrayFeatureResponse_<ContainerAllocator> Type;

  GetFloatArrayFeatureResponse_()
    : feature()  {
    }
  GetFloatArrayFeatureResponse_(const ContainerAllocator& _alloc)
    : feature(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _feature_type;
  _feature_type feature;





  typedef boost::shared_ptr< ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetFloatArrayFeatureResponse_

typedef ::pr2_robot::GetFloatArrayFeatureResponse_<std::allocator<void> > GetFloatArrayFeatureResponse;

typedef boost::shared_ptr< ::pr2_robot::GetFloatArrayFeatureResponse > GetFloatArrayFeatureResponsePtr;
typedef boost::shared_ptr< ::pr2_robot::GetFloatArrayFeatureResponse const> GetFloatArrayFeatureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pr2_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'pr2_robot': ['/home/gina/robot_ws/src/RoboND-Perception-Project/pr2_robot/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "294d40af1af59d3ff9b78d3a0d06f00c";
  }

  static const char* value(const ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x294d40af1af59d3fULL;
  static const uint64_t static_value2 = 0xf9b78d3a0d06f00cULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr2_robot/GetFloatArrayFeatureResponse";
  }

  static const char* value(const ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] feature\n\
\n\
";
  }

  static const char* value(const ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFloatArrayFeatureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr2_robot::GetFloatArrayFeatureResponse_<ContainerAllocator>& v)
  {
    s << indent << "feature[]" << std::endl;
    for (size_t i = 0; i < v.feature.size(); ++i)
    {
      s << indent << "  feature[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.feature[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR2_ROBOT_MESSAGE_GETFLOATARRAYFEATURERESPONSE_H
