// Generated by gencpp from file pr2_robot/GetNormals.msg
// DO NOT EDIT!


#ifndef PR2_ROBOT_MESSAGE_GETNORMALS_H
#define PR2_ROBOT_MESSAGE_GETNORMALS_H

#include <ros/service_traits.h>


#include <pr2_robot/GetNormalsRequest.h>
#include <pr2_robot/GetNormalsResponse.h>


namespace pr2_robot
{

struct GetNormals
{

typedef GetNormalsRequest Request;
typedef GetNormalsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNormals
} // namespace pr2_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pr2_robot::GetNormals > {
  static const char* value()
  {
    return "0a9bb8a1d7550c14c769843382adf4ac";
  }

  static const char* value(const ::pr2_robot::GetNormals&) { return value(); }
};

template<>
struct DataType< ::pr2_robot::GetNormals > {
  static const char* value()
  {
    return "pr2_robot/GetNormals";
  }

  static const char* value(const ::pr2_robot::GetNormals&) { return value(); }
};


// service_traits::MD5Sum< ::pr2_robot::GetNormalsRequest> should match 
// service_traits::MD5Sum< ::pr2_robot::GetNormals > 
template<>
struct MD5Sum< ::pr2_robot::GetNormalsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pr2_robot::GetNormals >::value();
  }
  static const char* value(const ::pr2_robot::GetNormalsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pr2_robot::GetNormalsRequest> should match 
// service_traits::DataType< ::pr2_robot::GetNormals > 
template<>
struct DataType< ::pr2_robot::GetNormalsRequest>
{
  static const char* value()
  {
    return DataType< ::pr2_robot::GetNormals >::value();
  }
  static const char* value(const ::pr2_robot::GetNormalsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pr2_robot::GetNormalsResponse> should match 
// service_traits::MD5Sum< ::pr2_robot::GetNormals > 
template<>
struct MD5Sum< ::pr2_robot::GetNormalsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pr2_robot::GetNormals >::value();
  }
  static const char* value(const ::pr2_robot::GetNormalsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pr2_robot::GetNormalsResponse> should match 
// service_traits::DataType< ::pr2_robot::GetNormals > 
template<>
struct DataType< ::pr2_robot::GetNormalsResponse>
{
  static const char* value()
  {
    return DataType< ::pr2_robot::GetNormals >::value();
  }
  static const char* value(const ::pr2_robot::GetNormalsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PR2_ROBOT_MESSAGE_GETNORMALS_H
