(cl:defpackage pr2_robot-srv
  (:use )
  (:export
   "GETFLOATARRAYFEATURE"
   "<GETFLOATARRAYFEATURE-REQUEST>"
   "GETFLOATARRAYFEATURE-REQUEST"
   "<GETFLOATARRAYFEATURE-RESPONSE>"
   "GETFLOATARRAYFEATURE-RESPONSE"
   "GETNORMALS"
   "<GETNORMALS-REQUEST>"
   "GETNORMALS-REQUEST"
   "<GETNORMALS-RESPONSE>"
   "GETNORMALS-RESPONSE"
   "GRASP"
   "<GRASP-REQUEST>"
   "GRASP-REQUEST"
   "<GRASP-RESPONSE>"
   "GRASP-RESPONSE"
   "PICKPLACE"
   "<PICKPLACE-REQUEST>"
   "PICKPLACE-REQUEST"
   "<PICKPLACE-RESPONSE>"
   "PICKPLACE-RESPONSE"
  ))

